// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// The `spice` plugin's OWN CUE schema — the typed plugin_input for the `spice`
// SPICE-wire check verb. It is the SINGLE SOURCE for this plugin's params, used
// two ways (the same contract core `spec` and the http plugin use):
//
//  1. GENERATE the Go param struct — `cue exp gengotypes` (driven by the cue:gen
//     pipeline, which wraps this with `package params` + `@go(params)`) emits
//     ../params/cue_types_gen.go, so the provider decodes plugin_input into a
//     TYPED struct, never a hand-parsed map.
//  2. VALIDATE authored input AT RUNTIME — the plugin serves this source over the
//     Describe channel; the host splices it onto the base (base ++ plugin) and
//     validates every authored `spice:` step's plugin_input against #SpiceInput.
//
// Since the schema-compaction cutover the per-verb fields LEFT core #Op: an
// authored `spice: <method>` step (scalar sugar) or `spice: {method: …, x: …}`
// (map form) desugars to the INTERNAL plugin/plugin_input envelope, and every
// spice-exclusive modifier lives HERE — the former core #SpiceMethod enum is
// this def's `method` field. The shared assertion matchers
// (exit_status/stdout/stderr) and the general `timeout` stay on core #Op, read
// off the step Op by the provider.
//
// SELF-CONTAINED: it references NO base def, so it compiles standalone
// (gengotypes + the load-gate compile) AND splices onto the base (base ++ plugin
// is a def-name collision check, not a base-reference resolver).
type SpiceInput struct {
	// method — the spice method to dispatch (the former core #SpiceMethod enum;
	// also the scalar-sugar primary: `spice: <method>`).
	Method string `json:"method" yaml:"method,omitempty"`

	// action — start|stop for a record session (record); start|stop|status for a
	// session (session). record start begins capturing the display framebuffer at
	// fps into an MJPEG stream; record stop flushes it to artifact.
	Action string `json:"action,omitempty" yaml:"action,omitempty,omitempty"`

	// record_name — the recording session name (default "default"); multiple
	// concurrent sessions supported.
	RecordName string `json:"record_name,omitempty" yaml:"record_name,omitempty,omitempty"`

	// fps — the display-frame capture rate for record (default 5).
	Fps int `json:"fps,omitempty" yaml:"fps,omitempty,omitempty"`

	// x / y — guest-absolute coordinates (click/mouse).
	X int `json:"x,omitempty" yaml:"x,omitempty,omitempty"`

	Y int `json:"y,omitempty" yaml:"y,omitempty,omitempty"`

	// button — the mouse button for click (left/right/middle; default left).
	Button string `json:"button,omitempty" yaml:"button,omitempty,omitempty"`

	// text — the text `type` types (PC-AT scancode sequence).
	Text string `json:"text,omitempty" yaml:"text,omitempty,omitempty"`

	// key — the named key `key` presses.
	KeyName string `json:"key,omitempty" yaml:"key,omitempty,omitempty"`

	// artifact — the host path `screenshot`/`cursor` writes the PNG to.
	Artifact string `json:"artifact,omitempty" yaml:"artifact,omitempty,omitempty"`

	// artifact_min_bytes / artifact_min_dimensions / artifact_not_uniform — the
	// post-run artifact-reality assertions (sdk.RunArtifactValidators).
	ArtifactMinBytes int `json:"artifact_min_bytes,omitempty" yaml:"artifact_min_bytes,omitempty,omitempty"`

	ArtifactMinDimensions string `json:"artifact_min_dimensions,omitempty" yaml:"artifact_min_dimensions,omitempty,omitempty"`

	ArtifactNotUniform bool `json:"artifact_not_uniform,omitempty" yaml:"artifact_not_uniform,omitempty,omitempty"`

	// session — the DETACHED host-side recorder (Cutover A, A-task-2b): `spice: session` starts
	// the plugin's OWN binary in recorder mode through the runner's generic
	// background-session service (plugin-check's verb:session seam). The recorder
	// holds the SPICE wire itself — the provider stays wire-free — polls the display
	// at fps into state_dir/frames.mjpeg, and on SIGTERM finalizes with the FINAL
	// marker + the evidence row.json. venue/phase are stamped into the evidence row.
	SessionId string `json:"session_id,omitempty" yaml:"session_id,omitempty,omitempty"`

	StateDir string `json:"state_dir,omitempty" yaml:"state_dir,omitempty,omitempty"`

	// artifact_dir — the runner-injected generic evidence-artifact dir (verb-agnostic;
	// the provider appends its own filename/extension).
	ArtifactDir string `json:"artifact_dir,omitempty" yaml:"artifact_dir,omitempty,omitempty"`

	LogDir string `json:"log_dir,omitempty" yaml:"log_dir,omitempty,omitempty"`

	Venue string `json:"venue,omitempty" yaml:"venue,omitempty,omitempty"`

	Phase string `json:"phase,omitempty" yaml:"phase,omitempty,omitempty"`
}
