// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// The `spice` plugin's OWN CUE schema — the typed plugin_input for the `spice`
// SPICE-wire check verb. It is the SINGLE SOURCE for this plugin's params, used
// two ways (the same contract core `spec` and the http plugin use):
//
//  1. GENERATE the Go param struct — `cue exp gengotypes` (driven by the cue:gen
//     pipeline, which wraps this with `package params` + `@go(params)`) emits
//     ../params/cue_types_gen.go, so the provider decodes plugin_input into a
//     TYPED struct, never a hand-parsed map.
//  2. VALIDATE authored input AT RUNTIME — the plugin serves this source over the
//     Describe channel; the host splices it onto the base (base ++ plugin) and
//     validates every authored `spice:` step's plugin_input against #SpiceInput.
//
// Since the schema-compaction cutover the per-verb fields LEFT core #Op: an
// authored `spice: <method>` step (scalar sugar) or `spice: {method: …, x: …}`
// (map form) desugars to the INTERNAL plugin/plugin_input envelope, and every
// spice-exclusive modifier lives HERE — the former core #SpiceMethod enum is
// this def's `method` field. The shared assertion matchers
// (exit_status/stdout/stderr) and the general `timeout` stay on core #Op, read
// off the step Op by the provider.
//
// SELF-CONTAINED: it references NO base def, so it compiles standalone
// (gengotypes + the load-gate compile) AND splices onto the base (base ++ plugin
// is a def-name collision check, not a base-reference resolver).
type SpiceInput struct {
	// method — the spice method to dispatch (the former core #SpiceMethod enum;
	// also the scalar-sugar primary: `spice: <method>`).
	Method string `yaml:"method,omitempty" json:"method"`

	// action — start|stop for a record session (record); start|stop|status for a
	// session (session). record start begins capturing the display framebuffer at
	// fps into an MJPEG stream; record stop flushes it to artifact.
	Action string `yaml:"action,omitempty" json:"action,omitempty"`

	// record_name — the recording session name (default "default"); multiple
	// concurrent sessions supported.
	RecordName string `yaml:"record_name,omitempty" json:"record_name,omitempty"`

	// fps — the display-frame capture rate for record (default 5).
	Fps int `yaml:"fps,omitempty" json:"fps,omitempty"`

	// x / y — guest-absolute coordinates (click/mouse).
	X int `yaml:"x,omitempty" json:"x,omitempty"`

	Y int `yaml:"y,omitempty" json:"y,omitempty"`

	// button — the mouse button for click (left/right/middle; default left).
	Button string `yaml:"button,omitempty" json:"button,omitempty"`

	// text — the text `type` types (PC-AT scancode sequence).
	Text string `yaml:"text,omitempty" json:"text,omitempty"`

	// key — the named key `key` presses.
	KeyName string `yaml:"key,omitempty" json:"key,omitempty"`

	// artifact — the host path `screenshot`/`cursor` writes the PNG to.
	Artifact string `yaml:"artifact,omitempty" json:"artifact,omitempty"`

	// artifact_min_bytes / artifact_min_dimensions / artifact_not_uniform — the
	// post-run artifact-reality assertions (sdk.RunArtifactValidators).
	ArtifactMinBytes int `yaml:"artifact_min_bytes,omitempty" json:"artifact_min_bytes,omitempty"`

	ArtifactMinDimensions string `yaml:"artifact_min_dimensions,omitempty" json:"artifact_min_dimensions,omitempty"`

	ArtifactNotUniform bool `yaml:"artifact_not_uniform,omitempty" json:"artifact_not_uniform,omitempty"`

	// session — the DETACHED host-side recorder (Cutover A, A-task-2b): `spice: session` starts
	// the plugin's OWN binary in recorder mode through the runner's generic
	// background-session service (plugin-check's verb:session seam). The recorder
	// holds the SPICE wire itself — the provider stays wire-free — polls the display
	// at fps into state_dir/frames.mjpeg, and on SIGTERM finalizes with the FINAL
	// marker + the evidence row.json. venue/phase are stamped into the evidence row.
	SessionId string `yaml:"session_id,omitempty" json:"session_id,omitempty"`

	StateDir string `yaml:"state_dir,omitempty" json:"state_dir,omitempty"`

	// artifact_dir — the runner-injected generic evidence-artifact dir (verb-agnostic;
	// the provider appends its own filename/extension).
	ArtifactDir string `yaml:"artifact_dir,omitempty" json:"artifact_dir,omitempty"`

	LogDir string `yaml:"log_dir,omitempty" json:"log_dir,omitempty"`

	Venue string `yaml:"venue,omitempty" json:"venue,omitempty"`

	Phase string `yaml:"phase,omitempty" json:"phase,omitempty"`

	// --- console wizard: drive a text-console wizard on the VM's SPICE console
	// via the SHARED console engine (sdk/kit ConsoleWizard) — the SAME engine and
	// the SAME recipe the JetKVM verb uses (R3). steps: inline, or device:+recipe:
	// referencing a transport-neutral console-recipe entity.
	Steps []SpiceConsoleStep `yaml:"steps,omitempty" json:"steps,omitempty"`

	Device string `yaml:"device,omitempty" json:"device,omitempty"`

	Recipe string `yaml:"recipe,omitempty" json:"recipe,omitempty"`

	Answers map[string]string `yaml:"answers,omitempty" json:"answers,omitempty"`

	// --- console terminal session + flow (the GENERIC actions) -------------
	// The SAME generic console actions the `jetkvm:` verb exposes, over the
	// SHARED sdk/kit action layer (R3): open a terminal, run commands and read
	// their OCR output (with sudo), close it, enter a disk-encryption passphrase,
	// set the boot order, and drive a bounded flow. One authored action drives a
	// VM console over SPICE or a physical machine over a JetKVM.
	TerminalCombo string `yaml:"terminal_combo,omitempty" json:"terminal_combo,omitempty"`

	PromptAnchors []string `yaml:"prompt_anchors,omitempty" json:"prompt_anchors,omitempty"`

	Commands []SpiceSessionCommand `yaml:"commands,omitempty" json:"commands,omitempty"`

	CloseTerminal bool `yaml:"close_terminal,omitempty" json:"close_terminal,omitempty"`

	SudoPassword string `yaml:"sudo_password,omitempty" json:"sudo_password,omitempty"`

	SudoPasswordSecret string `yaml:"sudo_password_secret,omitempty" json:"sudo_password_secret,omitempty"`

	Passphrase string `yaml:"passphrase,omitempty" json:"passphrase,omitempty"`

	PassphraseSecret string `yaml:"passphrase_secret,omitempty" json:"passphrase_secret,omitempty"`

	Outcomes []string `yaml:"outcomes,omitempty" json:"outcomes,omitempty"`

	BootOrderAction string `yaml:"boot_order_action,omitempty" json:"boot_order_action,omitempty"`

	BootOrderEntry string `yaml:"boot_order_entry,omitempty" json:"boot_order_entry,omitempty"`

	BootOrderSequence string `yaml:"boot_order_sequence,omitempty" json:"boot_order_sequence,omitempty"`

	BootOrderCommand string `yaml:"boot_order_command,omitempty" json:"boot_order_command,omitempty"`

	FlowStart string `yaml:"flow_start,omitempty" json:"flow_start,omitempty"`

	FlowNodes map[string]SpiceFlowNode `yaml:"flow_nodes,omitempty" json:"flow_nodes,omitempty"`

	FlowMaxSteps int `yaml:"flow_max_steps,omitempty" json:"flow_max_steps,omitempty"`

	FlowMaxLoops int `yaml:"flow_max_loops,omitempty" json:"flow_max_loops,omitempty"`

	// flow_resume — auto-detect the entry node from the CURRENT screen.
	FlowResume bool `yaml:"flow_resume,omitempty" json:"flow_resume,omitempty"`

	FlowResumeOrder []string `yaml:"flow_resume_order,omitempty" json:"flow_resume_order,omitempty"`
}

// #SpiceConsoleStep — ONE step of a console-wizard recipe (the neutral shape,
// mirrored from kit.ConsoleStep).
type SpiceConsoleStep struct {
	WaitFor string `yaml:"wait_for,omitempty" json:"wait_for"`

	Action string `yaml:"action,omitempty" json:"action,omitempty"`

	KeyName string `yaml:"key,omitempty" json:"key,omitempty"`

	Combo string `yaml:"combo,omitempty" json:"combo,omitempty"`

	Text string `yaml:"text,omitempty" json:"text,omitempty"`

	TimeoutSec int `yaml:"timeout_sec,omitempty" json:"timeout_sec,omitempty"`

	Optional bool `yaml:"optional,omitempty" json:"optional,omitempty"`

	Artifact string `yaml:"artifact,omitempty" json:"artifact,omitempty"`

	Description string `yaml:"description,omitempty" json:"description,omitempty"`
}

// #SpiceSessionCommand — ONE command `run-command` runs in an open terminal
// (mirrored from kit.ConsoleCommand).
type SpiceSessionCommand struct {
	Command string `yaml:"command,omitempty" json:"command"`

	Sudo bool `yaml:"sudo,omitempty" json:"sudo,omitempty"`

	Expect string `yaml:"expect,omitempty" json:"expect,omitempty"`

	TimeoutSec int `yaml:"timeout_sec,omitempty" json:"timeout_sec,omitempty"`

	Artifact string `yaml:"artifact,omitempty" json:"artifact,omitempty"`

	Description string `yaml:"description,omitempty" json:"description,omitempty"`
}

// #SpiceFlowNode — ONE state of a console flow.
type SpiceFlowNode struct {
	Description string `yaml:"description,omitempty" json:"description,omitempty"`

	Wait []SpiceFlowOutcome `yaml:"wait,omitempty" json:"wait,omitempty"`

	Key string `yaml:"key,omitempty" json:"key,omitempty"`

	Combo string `yaml:"combo,omitempty" json:"combo,omitempty"`

	Text string `yaml:"text,omitempty" json:"text,omitempty"`

	Command string `yaml:"command,omitempty" json:"command,omitempty"`

	Sudo bool `yaml:"sudo,omitempty" json:"sudo,omitempty"`

	Expect string `yaml:"expect,omitempty" json:"expect,omitempty"`

	CloseTerminal bool `yaml:"close_terminal,omitempty" json:"close_terminal,omitempty"`

	Transitions map[string]string `yaml:"transitions,omitempty" json:"transitions,omitempty"`

	Next string `yaml:"next,omitempty" json:"next,omitempty"`

	Artifact string `yaml:"artifact,omitempty" json:"artifact,omitempty"`

	TimeoutSec int `yaml:"timeout_sec,omitempty" json:"timeout_sec,omitempty"`
}

// #SpiceFlowOutcome — ONE named condition a flow node waits for. It matches by
// OCR substring OR by a reference screenshot (perceptual hash).
type SpiceFlowOutcome struct {
	Name string `yaml:"name,omitempty" json:"name"`

	Match string `yaml:"match,omitempty" json:"match,omitempty"`

	Reference string `yaml:"reference,omitempty" json:"reference,omitempty"`

	MaxDistance int `yaml:"max_distance,omitempty" json:"max_distance,omitempty"`

	Failure bool `yaml:"failure,omitempty" json:"failure,omitempty"`
}

// #SpiceConsoleRecipe — the console-recipe bundle a `spice: wizard` step reads
// from a transport-neutral console-recipe entity (a `kind: jetkvm` entity, the
// recipe home BOTH transports share). It is the AUTHORED shape spice decodes;
// the shared engine (sdk/kit) holds no wire type, so the shape lives here.
type SpiceConsoleRecipe struct {
	Recipes map[string][]SpiceConsoleStep `yaml:"recipes,omitempty" json:"recipes,omitempty"`

	Steps []SpiceConsoleStep `yaml:"steps,omitempty" json:"steps,omitempty"`

	Answers map[string]string `yaml:"answers,omitempty" json:"answers,omitempty"`

	AnswersEnv map[string]string `yaml:"answers_env,omitempty" json:"answers_env,omitempty"`
}

// #SpiceConsoleRecipeEntity — the entity body half spice reads: the `installer`
// recipe bundle. The rest of the entity (host, device fields) belongs to the
// verb that OWNS the device (jetkvm); spice reads only the transport-neutral
// recipe.
type SpiceConsoleRecipeEntity struct {
	Installer *SpiceConsoleRecipe `yaml:"installer,omitempty" json:"installer,omitempty"`
}
