// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// The `spice` plugin's OWN CUE schema — the typed plugin_input for the `spice`
// SPICE-wire check verb. It is the SINGLE SOURCE for this plugin's params, used
// two ways (the same contract core `spec` and the http plugin use):
//
//  1. GENERATE the Go param struct — `cue exp gengotypes` (driven by the cue:gen
//     pipeline, which wraps this with `package params` + `@go(params)`) emits
//     ../params/cue_types_gen.go, so the provider decodes plugin_input into a
//     TYPED struct, never a hand-parsed map.
//  2. VALIDATE authored input AT RUNTIME — the plugin serves this source over the
//     Describe channel; the host splices it onto the base (base ++ plugin) and
//     validates every authored `spice:` step's plugin_input against #SpiceInput.
//
// Since the schema-compaction cutover the per-verb fields LEFT core #Op: an
// authored `spice: <method>` step (scalar sugar) or `spice: {method: …, x: …}`
// (map form) desugars to the INTERNAL plugin/plugin_input envelope, and every
// spice-exclusive modifier lives HERE — the former core #SpiceMethod enum is
// this def's `method` field. The shared assertion matchers
// (exit_status/stdout/stderr) and the general `timeout` stay on core #Op, read
// off the step Op by the provider.
//
// SELF-CONTAINED: it references NO base def, so it compiles standalone
// (gengotypes + the load-gate compile) AND splices onto the base (base ++ plugin
// is a def-name collision check, not a base-reference resolver).
type SpiceInput struct {
	// method — the spice method to dispatch (the former core #SpiceMethod enum;
	// also the scalar-sugar primary: `spice: <method>`).
	Method string `yaml:"method,omitempty" json:"method"`

	// x / y — guest-absolute coordinates (click/mouse).
	X int `yaml:"x,omitempty" json:"x,omitempty"`

	Y int `yaml:"y,omitempty" json:"y,omitempty"`

	// button — the mouse button for click (left/right/middle; default left).
	Button string `yaml:"button,omitempty" json:"button,omitempty"`

	// text — the text `type` types (PC-AT scancode sequence).
	Text string `yaml:"text,omitempty" json:"text,omitempty"`

	// key — the named key `key` presses.
	KeyName string `yaml:"key,omitempty" json:"key,omitempty"`

	// artifact — the host path `screenshot`/`cursor` writes the PNG to.
	Artifact string `yaml:"artifact,omitempty" json:"artifact,omitempty"`

	// artifact_min_bytes / artifact_min_dimensions / artifact_not_uniform — the
	// post-run artifact-reality assertions (sdk.RunArtifactValidators).
	ArtifactMinBytes int `yaml:"artifact_min_bytes,omitempty" json:"artifact_min_bytes,omitempty"`

	ArtifactMinDimensions string `yaml:"artifact_min_dimensions,omitempty" json:"artifact_min_dimensions,omitempty"`

	ArtifactNotUniform bool `yaml:"artifact_not_uniform,omitempty" json:"artifact_not_uniform,omitempty"`
}
